title: 林世揚<br>Shih-Yang Lin
description: Economics Ph.D. Student<br><br>Department of Economics<br>National Taiwan University<br>No.1, Sec 4, Roosevelt Rd.<br>Taipei 10617, Taiwan<br><br>Email&#58; d07323003@ntu.edu.tw
theme: jekyll-theme-minimal
