title: Shih-Yang Lin   林世揚
description: |
  Economics Ph.D. Student  
  National Taiwan University  
  
  Department of Economics  
  National Taiwan University  
  No.1, Sec 4, Roosevelt Rd.  
  Taipei 10617, Taiwan  
  
  d07323003@ntu.edu.tw
theme: jekyll-theme-minimal
