title: 林世揚<br>Shih-Yang Lin
description: Assistant Professor<br><br>Department of Economics<br>National Dong Hwa University<br>D408, Hmanities and Social Sciences Building II,<br>No. 1, Sec. 2, Da Hsueh Rd. Shoufeng<br>Hualien 974301, Taiwan<br><br>Email&#58; linsy@gms.ndhu.edu.tw
theme: jekyll-theme-minimal
